Module-2/Task-2
js-tasks-ru/jsbasic-20220124_slavka6 pull request #5
Opened 2022-02-03 11:13 UTC by SlavkaSlavka

2022-02-03 11:14 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-03 11:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-03 12:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-03 15:46 UTC, koalex requested changes
Несмотря на то, что тесты ОК нужно исправить мои замечания.

2022-02-03 15:46 UTC, koalex commented on 2-module/3-task/index.js
> +console.log(calculator.mul()); // 15
Надо не оставлять в коде `console.log`-и

2022-02-03 15:46 UTC, koalex commented on 2-module/2-task/index.js
> +alert( isEmpty(schedule) ); // true
Удалить `alert`

2022-02-03 15:46 UTC, koalex commented on 2-module/2-task/index.js
> +alert( isEmpty(schedule) ); // false
Удалить `alert`

2022-02-03 15:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-04 09:27 UTC, koalex approved these changes

2022-02-04 09:27 UTC, merged